export const TYPE_ORDER = Object.freeze(["ash", "bloom", "tide", "rust", "static"]);

export const TYPE_INFO = Object.freeze({
  ash: {
    label: "Ash",
    color: "#ff8f59",
    glyph: "A",
    strongAgainst: "bloom",
    weakAgainst: "static",
    summary: "Heat, glare, and reckless impact.",
  },
  bloom: {
    label: "Bloom",
    color: "#9adf74",
    glyph: "B",
    strongAgainst: "tide",
    weakAgainst: "ash",
    summary: "Growth, spores, and rotten resilience.",
  },
  tide: {
    label: "Tide",
    color: "#69d8f7",
    glyph: "T",
    strongAgainst: "rust",
    weakAgainst: "bloom",
    summary: "Cold pressure, wash, and momentum.",
  },
  rust: {
    label: "Rust",
    color: "#d49a63",
    glyph: "R",
    strongAgainst: "static",
    weakAgainst: "tide",
    summary: "Weight, salvage, and blunt force.",
  },
  static: {
    label: "Static",
    color: "#dbd46f",
    glyph: "S",
    strongAgainst: "ash",
    weakAgainst: "rust",
    summary: "Interference, stun, and sharp speed.",
  },
});

function deck(entries) {
  return Object.freeze(
    entries.reduce((result, [cardId, count]) => {
      result[cardId] = count;
      return result;
    }, {})
  );
}

export const CREATURES = Object.freeze([
  {
    id: "cinder-pup",
    name: "Cinder Pup",
    type: "ash",
    maxHp: 72,
    speed: 8,
    artKey: "cinder-pup",
    glyph: "CP",
    passive: { kind: "attack-inflicts-burn" },
    passiveText: "Every damaging attack from this creature ignites the target.",
    signatureCardIds: ["muzzle-of-cinders"],
    blurb: "A kennel reject that learned to bite sparks out of cable walls.",
  },
  {
    id: "kiln-ram",
    name: "Kiln Ram",
    type: "ash",
    maxHp: 98,
    speed: 4,
    artKey: "kiln-ram",
    glyph: "KR",
    passive: { kind: "enter-guard", amount: 9 },
    passiveText: "When it becomes active, gain 9 guard.",
    signatureCardIds: ["kiln-charge"],
    blurb: "Brick-lunged and furious, always arriving shoulder-first.",
  },
  {
    id: "ember-veil",
    name: "Ember Veil",
    type: "ash",
    maxHp: 80,
    speed: 7,
    artKey: "ember-veil",
    glyph: "EV",
    passive: { kind: "type-damage-bonus", amount: 6 },
    passiveText: "Ash attacks from this creature deal 6 extra damage.",
    signatureCardIds: ["veil-flare"],
    blurb: "A silk stack of ashes pretending to be a saint.",
  },
  {
    id: "rotbloom-doe",
    name: "Rotbloom Doe",
    type: "bloom",
    maxHp: 84,
    speed: 6,
    artKey: "rotbloom-doe",
    glyph: "RD",
    passive: { kind: "bench-heal", amount: 5 },
    passiveText: "At the end of your turn, heal 5 while benched.",
    signatureCardIds: ["doe-rehearsal"],
    blurb: "Its antlers grow soft flowers that smell like old rainwater.",
  },
  {
    id: "briar-toad",
    name: "Briar Toad",
    type: "bloom",
    maxHp: 92,
    speed: 4,
    artKey: "briar-toad",
    glyph: "BT",
    passive: { kind: "turn-start-guard", amount: 6 },
    passiveText: "At the start of your turn, if active, gain 6 guard.",
    signatureCardIds: ["bog-bastion"],
    blurb: "Bloated with seed sacks and impossible patience.",
  },
  {
    id: "mold-seer",
    name: "Mold Seer",
    type: "bloom",
    maxHp: 78,
    speed: 8,
    artKey: "mold-seer",
    glyph: "MS",
    passive: { kind: "switch-draw", amount: 1 },
    passiveText: "When switched in, draw 1 card.",
    signatureCardIds: ["false-spring"],
    blurb: "Its face is a petri dish of predictions and lies.",
  },
  {
    id: "glassfin-idol",
    name: "Glassfin Idol",
    type: "tide",
    maxHp: 74,
    speed: 9,
    artKey: "glassfin-idol",
    glyph: "GI",
    passive: { kind: "cleanse-on-enter" },
    passiveText: "When it becomes active, remove burn and stun from itself.",
    signatureCardIds: ["idol-wash"],
    blurb: "A ceremonial fish cast in wet porcelain and static prayer.",
  },
  {
    id: "brine-mantis",
    name: "Brine Mantis",
    type: "tide",
    maxHp: 82,
    speed: 7,
    artKey: "brine-mantis",
    glyph: "BM",
    passive: { kind: "faster-damage-bonus", amount: 6 },
    passiveText: "If faster than the defender, attacks deal 6 extra damage.",
    signatureCardIds: ["razor-current"],
    blurb: "A blade insect preserved in salt and spite.",
  },
  {
    id: "scrapjaw-hound",
    name: "Scrapjaw Hound",
    type: "rust",
    maxHp: 88,
    speed: 6,
    artKey: "scrapjaw-hound",
    glyph: "SH",
    passive: { kind: "bloodied-damage-bonus", amount: 7 },
    passiveText: "While at half health or less, attacks deal 7 extra damage.",
    signatureCardIds: ["scrap-hunt"],
    blurb: "Built out of trap teeth, bad welds, and a familiar grin.",
  },
  {
    id: "slag-tortoise",
    name: "Slag Tortoise",
    type: "rust",
    maxHp: 108,
    speed: 3,
    artKey: "slag-tortoise",
    glyph: "ST",
    passive: { kind: "flat-shield", amount: 4 },
    passiveText: "Reduce incoming damage by 4 before guard.",
    signatureCardIds: ["molten-shell"],
    blurb: "It drags a whole furnace room on its back.",
  },
  {
    id: "coil-crow",
    name: "Coil Crow",
    type: "static",
    maxHp: 76,
    speed: 9,
    artKey: "coil-crow",
    glyph: "CC",
    passive: { kind: "attack-inflicts-stun" },
    passiveText: "Every damaging attack from this creature overloads the target.",
    signatureCardIds: ["crow-arc"],
    blurb: "More wire than bird, but it still knows how to watch.",
  },
  {
    id: "neon-moth",
    name: "Neon Moth",
    type: "static",
    maxHp: 70,
    speed: 10,
    artKey: "neon-moth",
    glyph: "NM",
    passive: { kind: "attack-grants-guard", amount: 5 },
    passiveText: "After it attacks, gain 5 guard.",
    signatureCardIds: ["lumen-shed"],
    blurb: "A ruined club sign wearing itself like a body.",
  },
]);

export const CARDS = Object.freeze([
  {
    id: "ember-jab",
    name: "Ember Jab",
    category: "attack",
    energyCost: 1,
    typeRequirement: "ash",
    power: 14,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 14 damage and scorch the target.",
    effects: [{ kind: "apply-status", target: "enemy-active", status: "burn" }],
  },
  {
    id: "furnace-kick",
    name: "Furnace Kick",
    category: "attack",
    energyCost: 2,
    typeRequirement: "ash",
    power: 24,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 24 damage.",
    effects: [],
  },
  {
    id: "thorn-lash",
    name: "Thorn Lash",
    category: "attack",
    energyCost: 1,
    typeRequirement: "bloom",
    power: 13,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 13 damage, then gain 4 guard.",
    effects: [{ kind: "guard", target: "ally-active", amount: 4 }],
  },
  {
    id: "spore-bloom",
    name: "Spore Bloom",
    category: "attack",
    energyCost: 2,
    typeRequirement: "bloom",
    power: 21,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 21 damage and heal 6.",
    effects: [{ kind: "heal", target: "ally-active", amount: 6 }],
  },
  {
    id: "undertow-swipe",
    name: "Undertow Swipe",
    category: "attack",
    energyCost: 1,
    typeRequirement: "tide",
    power: 14,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 14 damage.",
    effects: [],
  },
  {
    id: "brine-pressure",
    name: "Brine Pressure",
    category: "attack",
    energyCost: 2,
    typeRequirement: "tide",
    power: 22,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 22 damage and inflict stun.",
    effects: [{ kind: "apply-status", target: "enemy-active", status: "stun" }],
  },
  {
    id: "scrap-pummel",
    name: "Scrap Pummel",
    category: "attack",
    energyCost: 1,
    typeRequirement: "rust",
    power: 15,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 15 damage.",
    effects: [],
  },
  {
    id: "iron-crush",
    name: "Iron Crush",
    category: "attack",
    energyCost: 2,
    typeRequirement: "rust",
    power: 24,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 24 damage and gain 6 guard.",
    effects: [{ kind: "guard", target: "ally-active", amount: 6 }],
  },
  {
    id: "spark-peck",
    name: "Spark Peck",
    category: "attack",
    energyCost: 1,
    typeRequirement: "static",
    power: 13,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 13 damage and inflict stun.",
    effects: [{ kind: "apply-status", target: "enemy-active", status: "stun" }],
  },
  {
    id: "voltage-dive",
    name: "Voltage Dive",
    category: "attack",
    energyCost: 2,
    typeRequirement: "static",
    power: 24,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 24 damage.",
    effects: [],
  },
  {
    id: "patch-gel",
    name: "Patch Gel",
    category: "support",
    energyCost: 1,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Heal your active creature for 16.",
    effects: [{ kind: "heal", target: "ally-active", amount: 16 }],
  },
  {
    id: "spore-knit",
    name: "Spore Knit",
    category: "support",
    energyCost: 1,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Give your active creature 12 guard.",
    effects: [{ kind: "guard", target: "ally-active", amount: 12 }],
  },
  {
    id: "cold-reboot",
    name: "Cold Reboot",
    category: "support",
    energyCost: 1,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Remove burn and stun, then draw 1.",
    effects: [
      { kind: "cleanse", target: "ally-active", statuses: ["burn", "stun"] },
      { kind: "draw", target: "self-side", amount: 1 },
    ],
  },
  {
    id: "salvage-loop",
    name: "Salvage Loop",
    category: "support",
    energyCost: 1,
    rarity: "common",
    targetMode: "self-side",
    effectText: "Draw 2 cards.",
    effects: [{ kind: "draw", target: "self-side", amount: 2 }],
  },
  {
    id: "ash-tonic",
    name: "Ash Tonic",
    category: "support",
    energyCost: 1,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Heal 10 and remove burn.",
    effects: [
      { kind: "heal", target: "ally-active", amount: 10 },
      { kind: "cleanse", target: "ally-active", statuses: ["burn"] },
    ],
  },
  {
    id: "static-mesh",
    name: "Static Mesh",
    category: "support",
    energyCost: 1,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Gain 8 guard and remove stun.",
    effects: [
      { kind: "guard", target: "ally-active", amount: 8 },
      { kind: "cleanse", target: "ally-active", statuses: ["stun"] },
    ],
  },
  {
    id: "iron-sutures",
    name: "Iron Sutures",
    category: "support",
    energyCost: 2,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Heal 24 and gain 6 guard.",
    effects: [
      { kind: "heal", target: "ally-active", amount: 24 },
      { kind: "guard", target: "ally-active", amount: 6 },
    ],
  },
  {
    id: "grave-pollen",
    name: "Grave Pollen",
    category: "support",
    energyCost: 1,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Heal 8 and draw 1.",
    effects: [
      { kind: "heal", target: "ally-active", amount: 8 },
      { kind: "draw", target: "self-side", amount: 1 },
    ],
  },
  {
    id: "ember-ampoule",
    name: "Ember Ampoule",
    category: "item",
    energyCost: 0,
    rarity: "common",
    targetMode: "enemy-active",
    effectText: "Deal 8 damage and inflict burn.",
    effects: [
      { kind: "damage", target: "enemy-active", amount: 8, typed: false },
      { kind: "apply-status", target: "enemy-active", status: "burn" },
    ],
  },
  {
    id: "bandage-kit",
    name: "Bandage Kit",
    category: "item",
    energyCost: 0,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Heal your active creature for 10.",
    effects: [{ kind: "heal", target: "ally-active", amount: 10 }],
  },
  {
    id: "null-capsule",
    name: "Null Capsule",
    category: "item",
    energyCost: 1,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Remove burn, stun, and guard penalties from your active creature.",
    effects: [{ kind: "cleanse", target: "ally-active", statuses: ["burn", "stun"] }],
  },
  {
    id: "guard-shard",
    name: "Guard Shard",
    category: "item",
    energyCost: 0,
    rarity: "common",
    targetMode: "ally-active",
    effectText: "Give your active creature 6 guard.",
    effects: [{ kind: "guard", target: "ally-active", amount: 6 }],
  },
  {
    id: "slipgate-step",
    name: "Slipgate Step",
    category: "switch",
    energyCost: 1,
    rarity: "common",
    targetMode: "ally-bench",
    effectText: "Switch your active creature with a benched creature.",
    effects: [{ kind: "switch", target: "ally-bench" }],
  },
  {
    id: "bench-relay",
    name: "Bench Relay",
    category: "switch",
    energyCost: 0,
    rarity: "common",
    targetMode: "ally-bench",
    effectText: "Switch, then draw 1.",
    effects: [
      { kind: "switch", target: "ally-bench" },
      { kind: "draw", target: "self-side", amount: 1 },
    ],
  },
  {
    id: "muzzle-of-cinders",
    name: "Muzzle of Cinders",
    category: "attack",
    energyCost: 2,
    typeRequirement: "ash",
    power: 27,
    rarity: "signature",
    signatureOwnerId: "cinder-pup",
    targetMode: "enemy-active",
    effectText: "Deal 27 damage and ignite the target.",
    effects: [{ kind: "apply-status", target: "enemy-active", status: "burn" }],
  },
  {
    id: "kiln-charge",
    name: "Kiln Charge",
    category: "attack",
    energyCost: 2,
    typeRequirement: "ash",
    power: 28,
    rarity: "signature",
    signatureOwnerId: "kiln-ram",
    targetMode: "enemy-active",
    effectText: "Deal 28 damage and gain 10 guard.",
    effects: [{ kind: "guard", target: "ally-active", amount: 10 }],
  },
  {
    id: "veil-flare",
    name: "Veil Flare",
    category: "attack",
    energyCost: 2,
    typeRequirement: "ash",
    power: 26,
    rarity: "signature",
    signatureOwnerId: "ember-veil",
    targetMode: "enemy-active",
    effectText: "Deal 26 damage, then draw 1.",
    effects: [{ kind: "draw", target: "self-side", amount: 1 }],
  },
  {
    id: "doe-rehearsal",
    name: "Doe Rehearsal",
    category: "support",
    energyCost: 1,
    rarity: "signature",
    signatureOwnerId: "rotbloom-doe",
    targetMode: "ally-active",
    effectText: "Heal 12 and gain 10 guard.",
    effects: [
      { kind: "heal", target: "ally-active", amount: 12 },
      { kind: "guard", target: "ally-active", amount: 10 },
    ],
  },
  {
    id: "bog-bastion",
    name: "Bog Bastion",
    category: "support",
    energyCost: 1,
    rarity: "signature",
    signatureOwnerId: "briar-toad",
    targetMode: "ally-active",
    effectText: "Gain 16 guard and heal 6.",
    effects: [
      { kind: "guard", target: "ally-active", amount: 16 },
      { kind: "heal", target: "ally-active", amount: 6 },
    ],
  },
  {
    id: "false-spring",
    name: "False Spring",
    category: "attack",
    energyCost: 2,
    typeRequirement: "bloom",
    power: 22,
    rarity: "signature",
    signatureOwnerId: "mold-seer",
    targetMode: "enemy-active",
    effectText: "Deal 22 damage and draw 1.",
    effects: [{ kind: "draw", target: "self-side", amount: 1 }],
  },
  {
    id: "idol-wash",
    name: "Idol Wash",
    category: "support",
    energyCost: 1,
    rarity: "signature",
    signatureOwnerId: "glassfin-idol",
    targetMode: "ally-active",
    effectText: "Heal 14, remove burn and stun, then draw 1.",
    effects: [
      { kind: "heal", target: "ally-active", amount: 14 },
      { kind: "cleanse", target: "ally-active", statuses: ["burn", "stun"] },
      { kind: "draw", target: "self-side", amount: 1 },
    ],
  },
  {
    id: "razor-current",
    name: "Razor Current",
    category: "attack",
    energyCost: 2,
    typeRequirement: "tide",
    power: 26,
    rarity: "signature",
    signatureOwnerId: "brine-mantis",
    targetMode: "enemy-active",
    effectText: "Deal 26 damage and inflict stun.",
    effects: [{ kind: "apply-status", target: "enemy-active", status: "stun" }],
  },
  {
    id: "scrap-hunt",
    name: "Scrap Hunt",
    category: "attack",
    energyCost: 2,
    typeRequirement: "rust",
    power: 29,
    rarity: "signature",
    signatureOwnerId: "scrapjaw-hound",
    targetMode: "enemy-active",
    effectText: "Deal 29 damage.",
    effects: [],
  },
  {
    id: "molten-shell",
    name: "Molten Shell",
    category: "support",
    energyCost: 1,
    rarity: "signature",
    signatureOwnerId: "slag-tortoise",
    targetMode: "ally-active",
    effectText: "Gain 20 guard.",
    effects: [{ kind: "guard", target: "ally-active", amount: 20 }],
  },
  {
    id: "crow-arc",
    name: "Crow Arc",
    category: "attack",
    energyCost: 2,
    typeRequirement: "static",
    power: 25,
    rarity: "signature",
    signatureOwnerId: "coil-crow",
    targetMode: "enemy-active",
    effectText: "Deal 25 damage and inflict stun.",
    effects: [{ kind: "apply-status", target: "enemy-active", status: "stun" }],
  },
  {
    id: "lumen-shed",
    name: "Lumen Shed",
    category: "item",
    energyCost: 0,
    rarity: "signature",
    signatureOwnerId: "neon-moth",
    targetMode: "ally-active",
    effectText: "Heal 8 and gain 8 guard.",
    effects: [
      { kind: "heal", target: "ally-active", amount: 8 },
      { kind: "guard", target: "ally-active", amount: 8 },
    ],
  },
]);

export const CARD_BY_ID = Object.freeze(
  Object.fromEntries(CARDS.map((card) => [card.id, card]))
);

export const CREATURE_BY_ID = Object.freeze(
  Object.fromEntries(CREATURES.map((creature) => [creature.id, creature]))
);

export const ENEMY_TRAINERS = Object.freeze([
  {
    id: "ward-nurse-hex",
    name: "Ward Nurse Hex",
    title: "Recovery Cultist",
    bio: "Keeps her squad alive long enough for the room to become yours instead.",
    squadIds: ["rotbloom-doe", "briar-toad", "glassfin-idol"],
    deckCounts: deck([
      ["thorn-lash", 2],
      ["spore-bloom", 2],
      ["patch-gel", 1],
      ["spore-knit", 2],
      ["cold-reboot", 2],
      ["iron-sutures", 2],
      ["grave-pollen", 2],
      ["bandage-kit", 2],
      ["guard-shard", 2],
      ["slipgate-step", 1],
      ["bench-relay", 1],
      ["doe-rehearsal", 2],
      ["bog-bastion", 2],
      ["idol-wash", 1],
    ]),
  },
  {
    id: "dockhand-vanta",
    name: "Dockhand Vanta",
    title: "Pressure Bruiser",
    bio: "His deck is all blunt tools and waterfront violence.",
    squadIds: ["scrapjaw-hound", "brine-mantis", "slag-tortoise"],
    deckCounts: deck([
      ["scrap-pummel", 2],
      ["iron-crush", 2],
      ["undertow-swipe", 2],
      ["brine-pressure", 2],
      ["spore-knit", 2],
      ["salvage-loop", 2],
      ["ember-ampoule", 2],
      ["guard-shard", 2],
      ["bandage-kit", 2],
      ["slipgate-step", 1],
      ["bench-relay", 1],
      ["razor-current", 2],
      ["scrap-hunt", 2],
    ]),
  },
  {
    id: "dr-quell",
    name: "Dr. Mercer Quell",
    title: "Lab Echo Engineer",
    bio: "A slow scientist with a fast deck and a terrible laugh.",
    squadIds: ["kiln-ram", "mold-seer", "coil-crow"],
    deckCounts: deck([
      ["ember-jab", 2],
      ["furnace-kick", 2],
      ["grave-pollen", 2],
      ["salvage-loop", 2],
      ["cold-reboot", 2],
      ["static-mesh", 2],
      ["bandage-kit", 2],
      ["null-capsule", 1],
      ["guard-shard", 2],
      ["spark-peck", 2],
      ["slipgate-step", 1],
      ["bench-relay", 1],
      ["kiln-charge", 2],
      ["crow-arc", 1],
    ]),
  },
  {
    id: "signal-prince-nix",
    name: "Signal Prince Nix",
    title: "Broadcast Duelist",
    bio: "Everything he does is fast, loud, and somehow still rehearsed.",
    squadIds: ["neon-moth", "ember-veil", "glassfin-idol"],
    deckCounts: deck([
      ["spark-peck", 2],
      ["voltage-dive", 2],
      ["ember-jab", 2],
      ["undertow-swipe", 2],
      ["patch-gel", 1],
      ["salvage-loop", 2],
      ["ember-ampoule", 2],
      ["guard-shard", 2],
      ["bandage-kit", 2],
      ["null-capsule", 1],
      ["slipgate-step", 1],
      ["bench-relay", 1],
      ["veil-flare", 2],
      ["lumen-shed", 2],
    ]),
  },
]);

export const ENEMY_TRAINER_BY_ID = Object.freeze(
  Object.fromEntries(ENEMY_TRAINERS.map((trainer) => [trainer.id, trainer]))
);

export const DEFAULT_PROFILE = Object.freeze({
  options: {
    reducedMotion: false,
  },
  selectedEnemyId: ENEMY_TRAINERS[0].id,
});

export const DEFAULT_LOADOUT = Object.freeze({
  squadIds: ["cinder-pup", "rotbloom-doe", "glassfin-idol"],
  deckCounts: deck([
    ["ember-jab", 2],
    ["thorn-lash", 2],
    ["undertow-swipe", 2],
    ["patch-gel", 2],
    ["spore-knit", 2],
    ["salvage-loop", 2],
    ["bandage-kit", 2],
    ["guard-shard", 2],
    ["ember-ampoule", 2],
    ["slipgate-step", 1],
    ["bench-relay", 1],
    ["muzzle-of-cinders", 1],
    ["doe-rehearsal", 1],
    ["idol-wash", 1],
    ["brine-pressure", 1],
  ]),
});

export function getDeckCardCount(deckCounts) {
  return Object.values(deckCounts).reduce((sum, count) => sum + count, 0);
}

export function getCardDeckLimit(card) {
  return card.rarity === "signature" ? 3 : 2;
}

export function getSquadSignatureCardIds(squadIds) {
  const signatureIds = [];
  squadIds.forEach((creatureId) => {
    const creature = CREATURE_BY_ID[creatureId];
    if (creature) {
      signatureIds.push(...creature.signatureCardIds);
    }
  });
  return signatureIds;
}

export function getAvailableCardsForSquad(squadIds) {
  const signatureIds = new Set(getSquadSignatureCardIds(squadIds));
  return CARDS.filter((card) => !card.signatureOwnerId || signatureIds.has(card.id));
}

export function normalizeDeckCounts(rawDeckCounts, squadIds) {
  const availableCardIds = new Set(getAvailableCardsForSquad(squadIds).map((card) => card.id));
  const normalized = {};

  Object.entries(rawDeckCounts || {}).forEach(([cardId, count]) => {
    const card = CARD_BY_ID[cardId];
    if (!card || !availableCardIds.has(cardId)) {
      return;
    }
    const safeCount = Math.max(0, Math.min(Number(count) || 0, getCardDeckLimit(card)));
    if (safeCount > 0) {
      normalized[cardId] = safeCount;
    }
  });

  return normalized;
}
